### ISSUE TITLE
requirements.txt missing

### ISSUE THREAD

**Issue by dptole** [richardclegg/vis_route#6]
Isn't there a way to facilitate downloading the dependencies using a `requirements.txt` file?

![image](https://user-images.githubusercontent.com/3951114/106469715-66e6f100-647e-11eb-98ef-5e657fb8e4eb.png)

I wanted to edit the source to alternate the colors of each line so that we could have a better picture of where the nodes are.

**Comment by richardclegg** [comment]
That will work on Linux, Mac and Windows for loads of different environments? I really doubt it is even possible. Surely not worth the effort for a little script like this.

**Comment by dptole** [comment]
Actually, as noted by tj-murphy on #1 I'm also struggling to install basemap correctly, too many compilation errors no matter which python version I try to use. You are right to be concerned about stability on different envs and waste too much time on such a little script. Aborting!

**Comment by richardclegg** [comment]
I didn't compile basemap but got it through pip. But that relies on people having pip (common but not inevitable).

**Comment by richardclegg** [comment]
Hope you are not offended by this issue being closed.

**Comment by dptole** [comment]
Of course im not offended lol xD. I recognize it would be too annoying trying to tidy things up for such a little script, not worth the effort. Don't worry
